### ISSUE TITLE
Unique properties of aggregates

### ISSUE THREAD

**Issue by angmar7772** [Product-Foundry/akka-cqrs#1]
Hi,

how do you solve an unique property of your aggregates? For example UserAggregate should have unique username and email. I have found some possibilities:  

1. User supervisor should store all taken usernames and emails and should reject CreateUser commands if they does not met unique constraints (fast and consistent, but supervisor must be persistent actor)  

2. Supervisor should ask read model and base on that, reject or forward message to aggregate (prevent creation of aggregate instance and eventually consistent)  

3. Aggregate instance should ask read model (for each command, new aggregate instance will be created and than validated agains read model, also eventually consistent)

**Comment by andrekampert** [comment]
In general, I think it makes sense to have no dependencies in aggregates. They are responsible for enforcing consistency within their context. Keeping track of state to decide on changing the aggregate collection is possible, but has some disadvantages. I think the biggest problem is that all updated need to be channeled through the same aggregate, making it harder to build a scaling distributed environment. 

1. It should be possible maintaining a collection of aggregates in another persistent actor to do this type of validation. In the current implementation, this is not too hard to add. Dependencies can be given to aggregates, so there could be a persistent UsersAggregate actor that keeps track of all users. Checking this actor to see if a username is unique can then be part of the aggregate validation.

2. Depending on your solution, it might be impossible to guarantee up-to-date projected state. Also, this creates a dependency from within your bounded domain context directly on your read model, which is probably not what you want. The check can be performed outside of the aggregate, though, for example in your controller. ProcessManagers can be used to fix potential problems in the rare event duplicates get created and trigger a compensating action.

3. I think the same reasoning applies as in 2.

**Comment by angmar7772** [comment]
Thank you very much. I forgot to mention an option to validate command outside of aggregate. Of course, there could be a "race condition" where two or more commands will pass that validation and therefore a ProcessManager can invoke a compensating action in order to fix that problem. Thank you
