### ISSUE TITLE
Testing support

### ISSUE THREAD

**Issue by dohnala** [Product-Foundry/akka-cqrs#15]
Hello,

I have some question about testing aggregates, process managers and projections. Currently I have these types of tests:

1. Unit tests for aggregates using **AggregateSupport** class
2. Unit tests for process managers using **ProcessManagerSupport** class
3. Unit tests for Rest api using spray

I wonder, how I can unit test my read model. I want assert that for given published events, read model is constructed/updated correctly and save to read store (mocked). Do you test your read model in your applications and if so, what approach do you use?

Do you also use some kind of integration tests, which will construct whole DomainContext with all aggregates, process managers and projections and than test it as a whole? Or you thing that it is necessary if you have properly unit tests for each component. I have application services between rest endpoint and my aggregates which validate command using read model or load some information from read model to enrich command. I wonder if I should use integration test for my application layer with initialized DomainContext(aggregates, process managers and projections), or unit test it in isolation.

**Comment by andrekampert** [comment]
- `AggregateSupport` provides some convenience in testing Aggregates. Events are collected, so I use it to send commands to an aggregate and validate if the commands got accepted and which events were produced
- `ProcessManagerSupport` creates the context for testing. You can provide events and check which commands were created  as a result of these events. Dependencies can be injected using a `ProcessManagerFactory` in your test cases
- 'Currently, for testing the read model, I am bypassing the aggregates altogether. I simply provide all events to the read model and build a projection, which I can test.One drawback is that I have to make sure the events I provide in my tests are logically correct. I've also seen examples where Scalacheck is used to create random valid combinations of events.

**Comment by dohnala** [comment]
Thank you
