### ISSUE TITLE
Process managers

### ISSUE THREAD

**Issue by dohnala** [Product-Foundry/akka-cqrs#26]
Hello,

I am trying implement some process managers. Tests are working fine. One of my aggregate is mixed with LocalEventPublisher in order to publish events to akka event stream. Next I have defined my ProcessManager extending SimpleProcessManager. When I run my app, my process manager does not consume any events published by my aggregate. What should I do in order to make my process manager to receive event publications from event stream? 

I have found ProcessManagerRegistryActor which is responsible for registering process managers and delivering event records to them, but it is not subscribed to event stream. How do you solve this problem problem? Are you implementing this yourself and it is not part of this library? 

Thanks

**Comment by andrekampert** [comment]
I use the following approach:

- Register processes with `ProcessManagerRegistry`
- Subscribe `ProcessManagerRegistry.actor` to the published events

In retrospect, this seems a bit clunky. My reasoning was that there are different ways to publish events, based on your particular needs, so feeding events to the registry is an application concern. Any suggestions for improvement are welcome.

**Comment by dohnala** [comment]
Ok ... thanks for you clarification. Currently I have problem with implementing AggregateRegistry. Can we talk in gitter, please?
